### ISSUE TITLE
preview in player not suitable for high res screens

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#117]
The player uses the thumbnail as preview image. As the Thumbnail already implies this is an low res image which looks terrible when scaled to a big player window.

One solution would be adding another image which is not a thumbnail and generate this image for all old releases or let the player generate an preview from the a fixed time in the video file.

**Comment by MaZderMind** [comment]
altough it would be best to generate the poster-image on the client, this seems to be pretty hard with current browser support (think: mobile devices). Also, as you know, our image-selection algorithm implements some logic on selecting one of multiple possible images from the video-file.

I would not say, that it's impossible to do this in the browser, but it would at least be impractical and not cross-browser compatible.

I'd instead suggest some kind of task, maybe a rake-task, to re-generate the thumbnails. Because the media.ccc.de-app and the cdn are now two completely separate systems, the rake-task could only generate the poster images in some folder, that would then need manual copying onto the cdn host.

This script should generate the posters in the native video-resolution. Also, the releasing-script should be changed to generate posters in native resolution for future releases.

**Comment by MaZderMind** [comment]
It would be easy to remove the poster in js as soon as the video is loaded and show the first frame instead, this would in most cases be the first frame of the prerole.

**Comment by derpeter** [comment]
This not necessary needs to be part of the app as mario didnt like this in the past.
We could do this just one for all files on media in a bash loop. For the future we can add that big image to the releasing.

**Comment by dedeibel** [comment]
I'll try to write a script to address this. Talked with MaZderMind that it would probably be best to increase thumbnail size and leave the padding to the webapp. The preview generation should be in full video dimensions.

**Comment by dedeibel** [comment]
Script to recreate the images: https://github.com/dedeibel/publishing/blob/feature/10-poster-image-full-resolution-recreate/postprocessing/rebuild_images/rebuild_images.pl

Ideally it would be run on a machine with fast access to the video files since the thumbnail script skims through each video file which takes forever remotely.

I hope to run it with help of MaZderMind once the discussion about the image processing app is done and  merged: https://github.com/voc/publishing/issues/10

**Comment by manno** [comment]
This is done I suppose?

**Comment by dedeibel** [comment]
Yes done, apparently I can't update the status.
