### ISSUE TITLE
Different JSON-Objects on public API in list and when requested directly via ID

### ISSUE THREAD

**Issue by NiciDieNase** [voc/voctoweb#227]
When I get the paginated lists of events or recordings via https://api.media.ccc.de/public/{events|recordings} the json-objects are different from the ones I get via the objects I get directly via public/{events|recordings}/{id}
For example the former ones contain view_count, downloaded_recordings_count and the list of related Events in the metadata field.
Also the lenth of the event is stored in lenght in one and duration in the other.

These inconsistencies make in kind of hard to work with the API. 

In addition I can't just query for a list of events belonging to a given conference (same for recordings for a given event). The only way to get this, is to go back to the conference

I know  /public/events and /public/recordings are not listed in the documentation for the public API, but they are kind of obvious.

**Comment by dedeibel** [comment]
Can you please post example URLs and responses?

**Comment by NiciDieNase** [comment]
https://api.media.ccc.de/public/events gives me this JSON
[events.json.txt](https://github.com/voc/voctoweb/files/870915/events.json.txt)

and for the first object out of that list:
https://api.media.ccc.de/public/events/3786 
the result is 
[events_3786.json.txt](https://github.com/voc/voctoweb/files/870920/events_3786.json.txt)

**Comment by dedeibel** [comment]
Sorry that you might have wasted some time there.

The most reliable way to get all information is to navigate from the conferences to the events or recordings.

https://api.media.ccc.de/public/conferences
https://api.media.ccc.de/public/conferences/87 (rustmcb)
-> events[0]
https://api.media.ccc.de/public/events/3786 (first entry, "Diesel")

I am not exactly sure if there is a reason why the events list does not contain the same information.

Technically it must be because of differences in the jbuilder definition

- https://github.com/voc/voctoweb/blob/431ed8efd86d6403fa8aa99c078438b2d383e8f6/app/views/public/shared/_event.json.jbuilder
- https://github.com/voc/voctoweb/blob/431ed8efd86d6403fa8aa99c078438b2d383e8f6/app/views/public/events/show.json.jbuilder

**Comment by manno** [comment]
Some of that might have been done to keep Json sizes small. Prefer linking
instead of nesting.

However we should check if there is a good compromise, so the API can still
be consumed by frameworks for example.

I guess adding fields should not disturb existing consumers like the kodi
plugin.

**Comment by NiciDieNase** [comment]
Some of the information that is only in the list obtained via /public/events would be really usefull if it was included in the list contained in /conferences/{id} (like view count, related events, promoted-flag)

I'm working on an app for FireTV/AndroidTV right now, and those would provide really nice options to link to related talks, use the recomendation features of android tv, list popular talks, etc

**Comment by manno** [comment]
> For example the former ones contain view_count, downloaded_recordings_count and the list of related That was actually a bug. Should be fixed in the PR.

> Also the lenth of the event is stored in lenght in one and duration in the other.
That's because we renamed the length field a few years back.. I added a duration field.


I currently can't test and deploy easily, maybe someone else from @voc can?

**Comment by NiciDieNase** [comment]
I don't know if it was this change or something else, but now the events, when retrieved via id (/public/events/[id]) don't contain the list of recordings anymore.

This definitively breaks things!

**Comment by NiciDieNase** [comment]
got fixed in #228
