### ISSUE TITLE
Private API: Caching on conference update

### ISSUE THREAD

**Issue by lukas2511** [voc/voctoweb#320]
I tried updating a conference using the private API and I was a bit confused about my changes not being applied.
After adding a few cache-breaking parameters to the public API URL I was able to see that the changes were actually applied. Since there is no error/ok message on update this was initially really confusing.

It would be great to either have a better API response with the actual changes or make it so that updating a conference automatically wipes corresponding cache entries so updates are live instantly.

**Comment by manno** [comment]
Update should report errors as well as success in the JSON:
https://github.com/voc/voctoweb/blob/ac514489495339b0d5f84fbfce3e6dc64fa5698e/app/controllers/api/conferences_controller.rb#L42

There is a lot of fragment caching, but changing the conference via `update` should certainly change `updated_at`.

But we do use edge caching in nginx, that's probably why cache-breaking params worked.

**Comment by lukas2511** [comment]
Update doesn't show any errors if there are unknown fields (e.g. `title`) in the request.
Also the return value only contains the conference id, that way I didn't get any feedback if my update actually worked and the public API was still returning the old value (i tested this by updating `aspect_ratio`).

Better API documentation could also be a workaround for this, because right now I basically had to guess how the request should be structured.

**Comment by manno** [comment]
I commented on the unknown parameters in https://github.com/voc/voctoweb/issues/319
Rails will ignore those params, adding an error for superfluous params is not easy and probably wrong.

I'd be happy to get a PR for better API documentation, otherwise use the source. The files I linked should contain all necessary information.

Since caching seems to work fine, I'm closing this. Thanks for reporting.
