### ISSUE TITLE
Allow more then 2 resolutions in the Download section

### ISSUE THREAD

**Issue by derpeter** [voc/voctoweb#456]
This talk https://media.ccc.de/v/chaotikum-beamerleinwand is available in UHD, HD and SD. The backend shows correctly all recordings (as well as the player) but the front end only shows two of them in the Download section.
Before FHD has been released UHD was shown but disappeared afterwards. 

Note: For tracker related reason the UHD file has the name HD where the FHD file is correctly called FHD.

Expected behavior: Show all available resolution in the Download section

**Comment by derchrisuk** [comment]
I don't have a working Voctoweb dev setup currently, but I think this line here is preventing the display of the other high quality video:

https://github.com/voc/voctoweb/blob/master/app/models/frontend/event.rb#L83

**Comment by saerdnaer** [comment]
Again this is implemented like that, due to browsers not supporting video files with multiple audio files, but we do not want to confuse the users with these files to the template picks only two files from the list:  

https://github.com/voc/voctoweb/blob/8b978f2f959ef95b68a5d7619038f703d8b36794/app/views/frontend/shared/_download.haml#L15-L36
